# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-03 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scientist', '0002_auto_20170902_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermailingaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.UserProfileInfo'),
        ),
    ]
