# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-13 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20170901_1605'),
        ('scientist', '0003_auto_20170902_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=128)),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=50)),
                ('grade', models.IntegerField()),
                ('stud_class', models.CharField(max_length=50)),
                ('interest_1', models.CharField(max_length=128)),
                ('interest_2', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserLetters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letterfile', models.FileField(blank=True, upload_to='letters')),
                ('date_of_upload', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.UserProfileInfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserStudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_being_matched', models.BooleanField(default=False)),
                ('is_matched', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scientist.StudentInfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.UserProfileInfo')),
            ],
        ),
    ]
