# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scientist', '0006_auto_20170914_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='userletters',
            name='description',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
