# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scientist', '0007_userletters_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLetters',
            new_name='ScientistLetters',
        ),
        migrations.RenameModel(
            old_name='UserMailingAddress',
            new_name='ScientistMailingAddress',
        ),
        migrations.RenameModel(
            old_name='UserStudentInfo',
            new_name='ScientistStudentInfo',
        ),
    ]
