# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scientist', '0008_auto_20170914_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scientistletters',
            name='user',
        ),
        migrations.RemoveField(
            model_name='scientiststudentinfo',
            name='student',
        ),
        migrations.RemoveField(
            model_name='scientiststudentinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='ScientistLetters',
        ),
        migrations.DeleteModel(
            name='ScientistStudentInfo',
        ),
        migrations.DeleteModel(
            name='StudentInfo',
        ),
    ]
