# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-25 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20170914_1203'),
        ('Students', '0004_auto_20170924_1457'),
        ('scientist', '0010_scientists'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('fulfilledDate', models.DateField(null=True)),
                ('isPending', models.BooleanField(default=True)),
                ('startingDate', models.DateField(null=True)),
                ('scientist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Requesting_scientist', to='registration.UserProfileInfo')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Matched_student', to='Students.Student')),
            ],
        ),
    ]
