# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0007_auto_20170914_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=50)),
                ('grade', models.IntegerField()),
                ('stud_class', models.CharField(max_length=50)),
                ('interest_1', models.CharField(max_length=128)),
                ('interest_2', models.CharField(max_length=128)),
                ('date_of_upload', models.DateField(auto_now_add=True)),
                ('scientist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assigned_scientist', to='registration.UserProfileInfo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teacher', to='registration.UserProfileInfo')),
            ],
        ),
    ]
