# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-04 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='ActiveDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='DeactiveDate',
            field=models.DateField(null=True),
        ),
    ]
