# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-24 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coordinator', '0002_auto_20180304_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='csvfiles')),
                ('creationDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
