# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-23 22:47
from __future__ import unicode_literals

import Letters.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0007_auto_20170914_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letterfile', models.FileField(blank=True, upload_to=Letters.models.user_directory_path)),
                ('date_of_upload', models.DateField(auto_now_add=True)),
                ('description', models.CharField(default=' ', max_length=100)),
                ('scientist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.UserProfileInfo')),
            ],
        ),
    ]
