# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20170817_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='is_matched',
            field=models.BooleanField(default=False),
        ),
    ]
