# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_usermailingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermailingaddress',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserMailingAddress',
        ),
    ]
